# ClientComm: Extract time from text

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from cfatools import *

## Load and process data

In [2]:
fname_messages = 'messages.csv'
messages = load_messages(fname_messages) # messages data
messages.head()

,client_id,user_id,id,body,number_from,number_to,inbound,twilio_status,read,created_at,...,sent,reporting_relationship_id,original_reporting_relationship_id,client_created_at,created_at_backup,send_at_backup,client_created_at_backup,created_at_num,send_at_num,client_created_at_num
0,1,1,34462,NaN,1.415795e+10,1.410422e+10,True,received,True,2018-06-28 08:45:49-04:00,...,False,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-28 19:45:49 TTT,TTT 2018-06-28 19:45:48 TTT,TTT 2017-08-11 23:44:30 TTT,1.530230e+09,1.530230e+09,1.502509e+09
1,1,1,40480,replied!,1.415795e+10,1.410422e+10,True,received,True,2018-08-03 06:44:26-04:00,...,False,1,1,2017-08-11 12:44:30-04:00,TTT 2018-08-03 17:44:26 TTT,TTT 2018-08-03 17:44:26 TTT,TTT 2017-08-11 23:44:30 TTT,1.533333e+09,1.533333e+09,1.502509e+09
2,1,1,14395,wokewjr\r\n,1.410422e+10,1.415795e+10,False,delivered,True,2018-03-28 03:12:42-04:00,...,True,1,1,2017-08-11 12:44:30-04:00,TTT 2018-03-28 14:12:42 TTT,TTT 2018-03-28 14:12:42 TTT,TTT 2017-08-11 23:44:30 TTT,1.522261e+09,1.522261e+09,1.502509e+09
3,1,1,809,send now from baltimore,1.410422e+10,1.415795e+10,False,delivered,True,2017-10-03 06:45:21-04:00,...,True,1,1,2017-08-11 12:44:30-04:00,TTT 2017-10-03 17:45:21 TTT,TTT 2017-10-03 17:45:21 TTT,TTT 2017-08-11 23:44:30 TTT,1.507067e+09,1.507067e+09,1.502509e+09
4,1,1,18622,Test mass message from Baltimore,1.410422e+10,1.415795e+10,False,delivered,True,2018-04-20 07:50:09-04:00,...,True,1,1,2017-08-11 12:44:30-04:00,TTT 2018-04-20 18:50:09 TTT,TTT 2018-04-20 18:50:09 TTT,TTT 2017-08-11 23:44:30 TTT,1.524265e+09,1.524265e+09,1.502509e+09

In [3]:
messages_with_dates_ext = messages.apply(find_dates_in_row,axis=1)

In [4]:
messages_with_dates_ext.head(100)

,client_id,user_id,id,body,number_from,number_to,inbound,twilio_status,read,created_at,...,reporting_relationship_id,original_reporting_relationship_id,client_created_at,created_at_backup,send_at_backup,client_created_at_backup,created_at_num,send_at_num,client_created_at_num,dates_ext
0,1,1,34462,NaN,1.415795e+10,1.410422e+10,True,received,True,2018-06-28 08:45:49-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-28 19:45:49 TTT,TTT 2018-06-28 19:45:48 TTT,TTT 2017-08-11 23:44:30 TTT,1.530230e+09,1.530230e+09,1.502509e+09,[]
1,1,1,40480,replied!,1.415795e+10,1.410422e+10,True,received,True,2018-08-03 06:44:26-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-08-03 17:44:26 TTT,TTT 2018-08-03 17:44:26 TTT,TTT 2017-08-11 23:44:30 TTT,1.533333e+09,1.533333e+09,1.502509e+09,[]
2,1,1,14395,wokewjr\r\n,1.410422e+10,1.415795e+10,False,delivered,True,2018-03-28 03:12:42-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-03-28 14:12:42 TTT,TTT 2018-03-28 14:12:42 TTT,TTT 2017-08-11 23:44:30 TTT,1.522261e+09,1.522261e+09,1.502509e+09,[]
3,1,1,809,send now from baltimore,1.410422e+10,1.415795e+10,False,delivered,True,2017-10-03 06:45:21-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-10-03 17:45:21 TTT,TTT 2017-10-03 17:45:21 TTT,TTT 2017-08-11 23:44:30 TTT,1.507067e+09,1.507067e+09,1.502509e+09,[]
4,1,1,18622,Test mass message from Baltimore,1.410422e+10,1.415795e+10,False,delivered,True,2018-04-20 07:50:09-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-04-20 18:50:09 TTT,TTT 2018-04-20 18:50:09 TTT,TTT 2017-08-11 23:44:30 TTT,1.524265e+09,1.524265e+09,1.502509e+09,[]
5,1,1,3869,Kfkskv,1.415795e+10,1.410422e+10,True,received,True,2017-12-18 08:08:58-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-12-18 20:08:58 TTT,TTT 2017-12-18 20:08:58 TTT,TTT 2017-08-11 23:44:30 TTT,1.513646e+09,1.513646e+09,1.502509e+09,[]
6,1,1,810,scheduled at 5:45pm ET to go out at 6pm ET,1.410422e+10,1.415795e+10,False,delivered,True,2017-10-03 06:46:05-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-10-03 17:46:05 TTT,TTT 2017-10-03 18:00:00 TTT,TTT 2017-08-11 23:44:30 TTT,1.507067e+09,1.507068e+09,1.502509e+09,[]
7,1,1,34461,NaN,1.415795e+10,1.410422e+10,True,received,True,2018-06-28 08:45:19-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-28 19:45:19 TTT,TTT 2018-06-28 19:45:19 TTT,TTT 2017-08-11 23:44:30 TTT,1.530230e+09,1.530230e+09,1.502509e+09,[]
8,1,1,3867,Hi Tomas,1.410422e+10,1.415795e+10,False,delivered,True,2017-12-18 08:08:37-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-12-18 20:08:37 TTT,TTT 2017-12-18 20:08:37 TTT,TTT 2017-08-11 23:44:30 TTT,1.513646e+09,1.513646e+09,1.502509e+09,[]
9,1,1,31034,trying to click multiple times,1.410422e+10,1.415795e+10,False,delivered,True,2018-06-14 06:00:54-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-14 17:00:54 TTT,TTT 2018-06-14 17:00:53 TTT,TTT 2017-08-11 23:44:30 TTT,1.529010e+09,1.529010e+09,1.502509e+09,[]
10,1,1,16764,before,1.410422e+10,1.415795e+10,False,delivered,True,2018-04-10 07:05:30-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-04-10 18:05:30 TTT,TTT 2018-04-10 18:05:30 TTT,TTT 2017-08-11 23:44:30 TTT,1.523398e+09,1.523398e+09,1.502509e+09,[]
11,1,1,41130,hello,1.410422e+10,1.415795e+10,False,delivered,True,2018-08-07 05:39:15-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-08-07 16:39:15 TTT,TTT 2018-08-07 16:39:15 TTT,TTT 2017-08-11 23:44:30 TTT,1.533674e+09,1.533674e+09,1.502509e+09,[]
12,1,1,3873,will this zero out?,1.410422e+10,1.415795e+10,False,delivered,True,2017-12-18 11:41:46-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-12-18 23:41:46 TTT,TTT 2017-12-19 09:00:00 TTT,TTT 2017-08-11 23:44:30 TTT,1.513659e+09,1.513692e+09,1.502509e+09,[]
13,1,1,244,Adjust,1.415795e+10,1.410422e+10,True,received,True,2017-08-30 05:48:46-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-08-30 16:48:46 TTT,TTT 2017-08-30 16:48:46 TTT,TTT 2017-08-11 23:44:30 TTT,1.504126e+09,1.504126e+09,1.502509e+09,[]
14,1,1,4646,hi me\r\n,1.410422e+10,1.415795e+10,False,delivered,True,2018-01-03 00:50:06-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-01-03 12:50:06 TTT,TTT 2018-01-03 12:50:06 TTT,TTT 2017-08-11 23:44:30 TTT,1.515002e+09,1.515002e+09,1.502509e+09,[]
15,1,1,3866,post-departments-update scheduled message!,1.410422e+10,1.415795e+10,False,NaN,True,2017-12-18 07:54:54-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-12-18 19:54:54 TTT,TTT 2017-12-18 21:00:00 TTT,TTT 2017-08-11 23:44:30 TTT,1.513645e+09,1.513649e+09,1.502509e+09,[]
16,1,1,41131,world,1.415795e+10,1.410422e+10,True,received,True,2018-08-07 05:39:32-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-08-07 16:39:32 TTT,TTT 2018-08-07 16:39:32 TTT,TTT 2017-08-11 23:44:30 TTT,1.533674e+09,1.533674e+09,1.502509e+09,[]
17,1,1,34460,hello,1.410422e+10,1.415795e+10,False,delivered,True,2018-06-28 08:44:10-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-28 19:44:10 TTT,TTT 2018-06-28 19:44:10 TTT,TTT 2017-08-11 23:44:30 TTT,1.530229e+09,1.530229e+09,1.502509e+09,[]
18,1,1,14333,bloop,1.410422e+10,1.415795e+10,False,delivered,True,2018-03-27 09:43:18-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-03-27 20:43:18 TTT,TTT 2018-03-27 20:43:18 TTT,TTT 2017-08-11 23:44:30 TTT,1.522198e+09,1.522198e+09,1.502509e+09,[]
19,1,1,3872,scheduled message from bmore at 8:30PST,1.410422e+10,1.415795e+10,False,delivered,True,2017-12-18 11:13:06-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-12-18 23:13:06 TTT,TTT 2017-12-18 23:30:00 TTT,TTT 2017-08-11 23:44:30 TTT,1.513657e+09,1.513658e+09,1.502509e+09,[]
20,1,1,243,Should,1.415795e+10,1.410422e+10,True,received,True,2017-08-30 05:48:27-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-08-30 16:48:27 TTT,TTT 2017-08-30 16:48:27 TTT,TTT 2017-08-11 23:44:30 TTT,1.504126e+09,1.504126e+09,1.502509e+09,[]
21,1,1,14334,Gift to my new house,1.415795e+10,1.410422e+10,True,received,True,2018-03-27 09:43:40-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-03-27 20:43:40 TTT,TTT 2018-03-27 20:43:40 TTT,TTT 2017-08-11 23:44:30 TTT,1.522198e+09,1.522198e+09,1.502509e+09,[]
22,1,1,1,hello from baltimore!,1.410422e+10,1.415795e+10,False,delivered,True,2017-08-11 12:44:40-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2017-08-11 23:44:40 TTT,TTT 2017-08-11 23:44:40 TTT,TTT 2017-08-11 23:44:30 TTT,1.502509e+09,1.502509e+09,1.502509e+09,[]
23,1,1,4647,Yep Djikase,1.415795e+10,1.410422e+10,True,received,True,2018-01-03 00:50:25-05:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-01-03 12:50:25 TTT,TTT 2018-01-03 12:50:25 TTT,TTT 2017-08-11 23:44:30 TTT,1.515002e+09,1.515002e+09,1.502509e+09,[]
24,1,1,34462,NaN,1.415795e+10,1.410422e+10,True,received,True,2018-06-28 08:45:49-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-28 19:45:49 TTT,TTT 2018-06-28 19:45:48 TTT,TTT 2017-08-11 23:44:30 TTT,1.530230e+09,1.530230e+09,1.502509e+09,[]
25,1,1,40479,from bmore,1.410422e+10,1.415795e+10,False,delivered,True,2018-08-03 06:44:05-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-08-03 17:44:05 TTT,TTT 2018-08-03 17:44:05 TTT,TTT 2017-08-11 23:44:30 TTT,1.533333e+09,1.533333e+09,1.502509e+09,[]
26,1,1,19420,mass message from baltimore,1.410422e+10,1.415795e+10,False,delivered,True,2018-04-25 06:41:33-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-04-25 17:41:33 TTT,TTT 2018-04-25 17:41:33 TTT,TTT 2017-08-11 23:44:30 TTT,1.524692e+09,1.524692e+09,1.502509e+09,[]
27,1,1,31018,ignore this test mass message from baltimore c...,1.410422e+10,1.415795e+10,False,delivered,True,2018-06-14 04:00:10-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-06-14 15:00:10 TTT,TTT 2018-06-14 15:00:10 TTT,TTT 2017-08-11 23:44:30 TTT,1.529003e+09,1.529003e+09,1.502509e+09,[]
28,1,1,16765,after,1.410422e+10,1.415795e+10,False,delivered,True,2018-04-10 07:08:26-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-04-10 18:08:26 TTT,TTT 2018-04-10 18:08:25 TTT,TTT 2017-08-11 23:44:30 TTT,1.523398e+09,1.523398e+09,1.502509e+09,[]
29,1,1,36895,bloop,1.410422e+10,1.415795e+10,False,delivered,True,2018-07-12 15:48:34-04:00,...,1,1,2017-08-11 12:44:30-04:00,TTT 2018-07-13 02:48:34 TTT,TTT 2018-07-13 02:48:34 TTT,TTT 2017-08-11 23:44:30 TTT,1.531465e+09,1.531465e+09,1.502509e+09,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,18,9,18420,Good Evening! This is Agent Adams just remindi...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-20 04:13:44-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-20 15:13:44 TTT,TTT 2018-04-20 15:12:58 TTT,TTT 2017-08-21 21:57:07 TTT,1.524252e+09,1.524252e+09,1.503367e+09,"[2018-04-23 03:00:00-04:00, 2018-08-15 18:00:0..."
71,18,9,28717,God Evening! This is Agent Adams from Pretrial...,1.410422e+10,1.443529e+10,False,delivered,True,2018-06-07 05:37:58-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-07 16:37:58 TTT,TTT 2018-06-07 16:37:46 TTT,TTT 2017-08-21 21:57:07 TTT,1.528404e+09,1.528404e+09,1.503367e+09,[]
72,18,9,23309,Good Evening! This is Agent Adams and I just w...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-15 05:03:25-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-15 16:03:25 TTT,TTT 2018-05-15 16:03:21 TTT,TTT 2017-08-21 21:57:07 TTT,1.526415e+09,1.526415e+09,1.503367e+09,[]
73,18,9,18355,Good Evening! This is Agent Adams just remindi...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-20 04:10:30-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-20 15:10:30 TTT,TTT 2018-04-20 15:09:51 TTT,TTT 2017-08-21 21:57:07 TTT,1.524251e+09,1.524251e+09,1.503367e+09,"[2018-04-23 03:00:00-04:00, 2018-08-15 18:00:0..."
74,18,9,17811,"Good Evening! This is Agent Adams , from Pretr...",1.410422e+10,1.443529e+10,False,delivered,True,2018-04-18 04:28:59-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-18 15:28:59 TTT,TTT 2018-04-18 15:28:32 TTT,TTT 2017-08-21 21:57:07 TTT,1.524080e+09,1.524080e+09,1.503367e+09,[]
75,18,9,24545,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:18:33-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:18:33 TTT,TTT 2018-05-18 16:18:23 TTT,TTT 2017-08-21 21:57:07 TTT,1.526675e+09,1.526675e+09,1.503367e+09,[]
76,18,9,26429,Good Eveniing! This is Agent Adams just sendin...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-24 05:15:02-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-24 16:15:02 TTT,TTT 2018-05-24 16:14:38 TTT,TTT 2017-08-21 21:57:07 TTT,1.527193e+09,1.527193e+09,1.503367e+09,"[2018-05-28 03:00:00-04:00, 2018-05-29 03:00:0..."
77,18,9,33031,Good Evening! This is Agent Adams just sendin...,1.410422e+10,1.443529e+10,False,delivered,True,2018-06-22 04:50:42-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-22 15:50:42 TTT,TTT 2018-06-22 15:50:03 TTT,TTT 2017-08-21 21:57:07 TTT,1.529697e+09,1.529697e+09,1.503367e+09,[]
78,18,9,357,"Good Afternoon! Mr. Jerrell Hill, this is Agen...",1.410422e+10,1.443529e+10,False,delivered,True,2017-09-11 02:31:37-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2017-09-11 13:31:37 TTT,TTT 2017-09-11 13:31:37 TTT,TTT 2017-08-21 21:57:07 TTT,1.505151e+09,1.505151e+09,1.503367e+09,"[2017-09-12 03:00:00-04:00, 2017-09-19 03:00:0..."
79,18,9,33078,Good Evening! This is Agent Adams just sendin...,1.410422e+10,1.443529e+10,False,delivered,True,2018-06-22 04:51:08-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-22 15:51:08 TTT,TTT 2018-06-22 15:50:35 TTT,TTT 2017-08-21 21:57:07 TTT,1.529697e+09,1.529697e+09,1.503367e+09,[]
80,18,9,24412,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:16:46-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:16:46 TTT,TTT 2018-05-18 16:16:38 TTT,TTT 2017-08-21 21:57:07 TTT,1.526675e+09,1.526675e+09,1.503367e+09,[]
81,18,9,19242,Good Evening! This is Agent Adams and just wan...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-24 03:24:17-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-24 14:24:17 TTT,TTT 2018-04-24 14:24:17 TTT,TTT 2017-08-21 21:57:07 TTT,1.524594e+09,1.524594e+09,1.503367e+09,[]
82,18,9,18306,Good Evening! This is Agent Adams just remindi...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-20 04:09:39-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-20 15:09:39 TTT,TTT 2018-04-20 15:08:59 TTT,TTT 2017-08-21 21:57:07 TTT,1.524251e+09,1.524251e+09,1.503367e+09,"[2018-04-23 03:00:00-04:00, 2018-08-15 18:00:0..."
83,18,9,24366,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:16:07-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:16:07 TTT,TTT 2018-05-18 16:16:00 TTT,TTT 2017-08-21 21:57:07 TTT,1.526675e+09,1.526675e+09,1.503367e+09,[]
84,18,9,37078,"Good Evening! Everone, this is a mass text jus...",1.410422e+10,1.443529e+10,False,delivered,True,2018-07-13 05:31:16-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-07-13 16:31:16 TTT,TTT 2018-07-13 16:31:15 TTT,TTT 2017-08-21 21:57:07 TTT,1.531514e+09,1.531514e+09,1.503367e+09,[]
85,18,9,38559,Good Evening! Just a friendly reminde rthat yo...,1.410422e+10,1.443529e+10,False,delivered,True,2018-07-20 03:52:59-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-07-20 14:52:59 TTT,TTT 2018-07-20 14:52:58 TTT,TTT 2017-08-21 21:57:07 TTT,1.532113e+09,1.532113e+09,1.503367e+09,[2018-07-03 03:00:00-04:00]
86,18,9,33888,"Good Evening! This is Agent Adam, Thank you so...",1.410422e+10,1.443529e+10,False,delivered,True,2018-06-26 04:38:34-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-26 15:38:34 TTT,TTT 2018-06-26 15:38:33 TTT,TTT 2017-08-21 21:57:07 TTT,1.530042e+09,1.530042e+09,1.503367e+09,[]
87,18,9,26022,Good Eveving! This is Agent Adams and this mes...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-23 05:38:44-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-23 16:38:44 TTT,TTT 2018-05-23 16:38:30 TTT,TTT 2017-08-21 21:57:07 TTT,1.527108e+09,1.527108e+09,1.503367e+09,[2018-05-24 03:00:00-04:00]
88,18,9,12111,Huh,1.443529e+10,1.410422e+10,True,received,True,2018-03-12 05:42:13-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-03-12 16:42:13 TTT,TTT 2018-03-12 16:42:13 TTT,TTT 2017-08-21 21:57:07 TTT,1.520887e+09,1.520887e+09,1.503367e+09,[]
89,18,9,24629,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:19:37-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:19:37 TTT,TTT 2018-05-18 16:19:29 TTT,TTT 2017-08-21 21:57:07 TTT,1.526675e+09,1.526675e+09,1.503367e+09,[]
90,18,9,30195,"To Everyone! This is Agent Adams, to all those...",1.410422e+10,1.443529e+10,False,delivered,True,2018-06-13 05:04:11-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-13 16:04:11 TTT,TTT 2018-06-13 16:03:51 TTT,TTT 2017-08-21 21:57:07 TTT,1.528920e+09,1.528920e+09,1.503367e+09,[2018-06-14 03:00:00-04:00]
91,18,9,24278,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:14:54-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:14:54 TTT,TTT 2018-05-18 16:14:46 TTT,TTT 2017-08-21 21:57:07 TTT,1.526674e+09,1.526674e+09,1.503367e+09,[]
92,18,9,19796,Hello! This is Agent Adams and I really would ...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-26 04:24:53-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-26 15:24:53 TTT,TTT 2018-04-26 15:24:48 TTT,TTT 2017-08-21 21:57:07 TTT,1.524771e+09,1.524771e+09,1.503367e+09,[]
93,18,9,36887,Good Evening! Thsi si Agent Adams Just wanted ...,1.410422e+10,1.443529e+10,False,delivered,True,2018-07-12 05:25:11-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-07-12 16:25:11 TTT,TTT 2018-07-12 16:25:03 TTT,TTT 2017-08-21 21:57:07 TTT,1.531427e+09,1.531427e+09,1.503367e+09,[]
94,18,9,38665,"My apologies! I noticed I made an error, your ...",1.410422e+10,1.443529e+10,False,delivered,True,2018-07-20 04:07:00-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-07-20 15:07:00 TTT,TTT 2018-07-20 15:07:00 TTT,TTT 2017-08-21 21:57:07 TTT,1.532114e+09,1.532114e+09,1.503367e+09,[2018-07-23 03:00:00-04:00]
95,18,9,35733,Good Evening! This is Agent Adasm just sending...,1.410422e+10,1.443529e+10,False,delivered,True,2018-07-06 04:13:43-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-07-06 15:13:43 TTT,TTT 2018-07-06 15:13:38 TTT,TTT 2017-08-21 21:57:07 TTT,1.530904e+09,1.530904e+09,1.503367e+09,"[2018-07-09 03:00:00-04:00, 2018-08-16 00:00:0..."
96,18,9,18459,Good Evening! This is Agent Adams just remindi...,1.410422e+10,1.443529e+10,False,delivered,True,2018-04-20 04:14:16-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-04-20 15:14:16 TTT,TTT 2018-04-20 15:13:32 TTT,TTT 2017-08-21 21:57:07 TTT,1.524252e+09,1.524252e+09,1.503367e+09,"[2018-04-23 03:00:00-04:00, 2018-08-15 18:00:0..."
97,18,9,24589,Good Evening! This is Agent Adams and just sen...,1.410422e+10,1.443529e+10,False,delivered,True,2018-05-18 05:19:07-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-18 16:19:07 TTT,TTT 2018-05-18 16:18:59 TTT,TTT 2017-08-21 21:57:07 TTT,1.526675e+09,1.526675e+09,1.503367e+09,[]
98,18,9,30073,"To Everyone! This is Agent Adams, to all those...",1.410422e+10,1.443529e+10,False,delivered,True,2018-06-13 05:02:22-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-06-13 16:02:22 TTT,TTT 2018-06-13 16:02:07 TTT,TTT 2017-08-21 21:57:07 TTT,1.528920e+09,1.528920e+09,1.503367e+09,[2018-06-14 03:00:00-04:00]
99,18,9,20708,Respond by mistake,1.443529e+10,1.410422e+10,True,received,True,2018-05-01 05:42:32-04:00,...,18,18,2017-08-21 10:57:07-04:00,TTT 2018-05-01 16:42:32 TTT,TTT 2018-05-01 16:42:32 TTT,TTT 2017-08-21 21:57:07 TTT,1.525207e+09,1.525207e+09,1.503367e+09,[]

In [5]:
messages_with_dates_ext.to_csv("messages.csv")